version: '3.9'

services:
  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      URI: mongodb://mongo_db:27017
      PORT: 3000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
